server:
  port: 8080

spring:
  application:
    name: poc-resource-aud-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}

security:
  oauth2:
    resource:
      id: resource-aud
      jwt:
        key-value: 123